version: '3'
services:
  serviceregistry:
    image: 'magnesiumsniper/serviceregistry:0.0.1'
    container_name: serviceregistry
    ports:
      - '8761:8761'
  configserver:
    image: 'magnesiumsniper/configserver:0.0.1'
    container_name: configserver
    ports:
      - '7072:7072'
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7072/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - serviceregistry
