server:
  port: 7073

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health
